#!/usr/bin/env bash

# This script normalizes input instances, adds their metadata and copies them
# to a specified output location
# The instances are copied to <outdir>/<family>/
#
# Usage: add-submission <author> <year> <family> <outdir> <instances ...>

set -euo pipefail

AUTHOR=$1
shift
YEAR=$1
shift
FAMILY=$1
shift
OUT_DIR=$1
shift

if [[ "$OUT_DIR" == */ ]]; then
  OUT_DIR="$OUT_DIR$FAMILY"
else
  OUT_DIR="$OUT_DIR/$FAMILY"
fi

>&2 echo "Adding $(ls -1 "$@" | wc -l) benchmark instances"

mkdir -p "$OUT_DIR"

for inst in "$@"; do
  if [[ "$inst" == *.gz ]]; then
    instname=$(basename "$inst" ".gz")
  elif [[ "$inst" == *.xz ]]; then
    instname=$(basename "$inst" ".xz")
  else
    instname=$(basename "$inst")
  fi
  idx=1
  outinstname="$instname.xz"
  while [[ -f "$OUT_DIR/$outinstname" ]]; do
    outinstname="$instname-$idx.xz"
    ((idx++))
    >&2 echo "File '$OUT_DIR/$outinstname' exists already"
  done
  std_wcnf "$inst" | xz > "$OUT_DIR/$outinstname"
  chmod 444 "$OUT_DIR/$outinstname"
done


gbd init --target wcnf_local -j8 local "$OUT_DIR"

gbd set "family=$FAMILY" "local like $OUT_DIR/%"
gbd set "submitted_in=$YEAR" "local like $OUT_DIR/%"
gbd set "submitted_by=$AUTHOR" "local like $OUT_DIR/%"
