#!/usr/bin/env bash

# This script normalizes input instances, adds their metadata and copies them
# to a specified output location
# The instances are copied to <outdir>/<family>/
#
# Usage: add-submission <author> <year> <family> <outdir> <indir>

set -euo pipefail

AUTHOR=$1
shift
YEAR=$1
shift
FAMILY=$1
shift
OUT_DIR=$1
shift
IN_DIR=$1
shift

mkdir -p "$OUT_DIR/$FAMILY"

OUT_DIR="$(realpath -e "$OUT_DIR/$FAMILY")"

>&2 echo "Adding $(find "$IN_DIR" \( -name '*.wcnf' -or -name '*.wcnf.gz' -or -name '*.wcnf.xz' \) | wc -l) benchmark instances"

FILENAMES=$(mktemp)

# Dummy database to not get problems when real DBs are locked
touch /tmp/dummy.csv

find "$IN_DIR" -name '*.wcnf' \
  -exec bash -c 'set -euo pipefail
    inst="$0"
    filename="${inst#$(realpath -e "$2")/}"
    mkdir -p "$1/$(dirname "$filename")"
    outfile="$1/$(dirname "$filename")/$(basename "$filename").xz"
    std_wcnf "$inst" | xz > "$outfile"
    chmod 444 "$outfile"
    echo "$(gbd -d /tmp/dummy.csv hash "$outfile");$filename"
  ' {} "$OUT_DIR" "$IN_DIR" \; >> "$FILENAMES"
find "$IN_DIR" -name '*.wcnf.gz' \
  -exec bash -c 'set -euo pipefail
    inst="$0"
    filename="${inst#$(realpath -e "$2")/}"
    mkdir -p "$1/$(dirname "$filename")"
    outfile="$1/$(dirname "$filename")/$(basename "$filename" ".gz").xz"
    std_wcnf "$inst" | xz > "$outfile"
    chmod 444 "$outfile"
    echo "$(gbd -d /tmp/dummy.csv hash "$outfile");$filename"
  ' {} "$OUT_DIR" "$IN_DIR" \; >> "$FILENAMES"
find "$IN_DIR" -name '*.wcnf.xz' \
  -exec bash -c 'set -euo pipefail
    inst="$0"
    filename="${inst#$(realpath -e "$2")/}"
    mkdir -p "$1/$(dirname "$filename")"
    outfile="$1/$(dirname "$filename")/$(basename "$filename" ".gz").xz"
    xz -dc "$inst" | std_wcnf | xz > "$outfile"
    chmod 444 "$outfile"
    echo "$(gbd -d /tmp/dummy.csv hash "$outfile");$filename"
  ' {} "$OUT_DIR" "$IN_DIR" \; >> "$FILENAMES"

gbd init --target wcnf_local -j8 local "$OUT_DIR"

gbd set "family=$FAMILY" "local like $OUT_DIR/%"
gbd set "submitted_in=$YEAR" "local like $OUT_DIR/%"
gbd set "submitted_by=$AUTHOR" "local like $OUT_DIR/%"

for line in $(cat "$FILENAMES"); do
  hash=$(echo $line | cut -d';' -f1)
  filename=$(echo $line | cut -d';' -f2)
  gbd set "submitted_as=$filename" --hashes "$hash"
done

rm "$FILENAMES"
