#!/usr/bin/env bash

set -euo pipefail

# Disqualify instances without sort clauses
gbd set "disqualified=yes" "s_clauses=0"

# Disqualify instances with unsat hard clauses
gbd set "disqualified=yes" "unsat=true"

# Disqualify random instances
gbd set "disqualified=yes" "used_in like %random%"

# Disqualify with optimal cost 0
gbd set "disqualified=yes" "optimal_cost=0 and not optimal_cost=unknown"

# Families that were decided to be excluded in previous MSEs

# Pathological case for IHS?
gbd set "disqualified=yes" "family=drmx-atmostk"

gbd set "disqualified=yes" "family=maximum-common-subgraph"

# Only consider newer submission
gbd set "disqualified=yes" "family=parametric-role-based-access-control-maintenance and submitted_in=2019"

# Random
gbd set "disqualified=yes" "family=set-covering"
gbd set "disqualified=yes" "family=max-clique"
gbd set "disqualified=yes" "family=max-cut"
gbd set "disqualified=yes" "family=max-csp"
gbd set "disqualified=yes" "family=max-one"
gbd set "disqualified=yes" "family=minimum-width-confidence-band"
